// Generated by CSS Grid Editor
import styled from 'styled-components'

export default styled.div`
width: 300px;
height: 100px;
display: grid;
grid-template-columns: 1fr 0.1fr 2fr;
grid-template-rows: 1fr 1fr;
grid-template-areas: 'g0 g1 g2' 'g3 g4 g5';
margin-top: 10px;
`;

export const g0 = styled.div`
grid-area: g0;
text-align: left;
`;

export const g1 = styled.div`
grid-area: g1;
text-align: left;
`;

export const g2 = styled.div`
grid-area: g2;
text-align: right;
`;

export const g3 = styled.div`
grid-area: g3;
text-align: left;
`;

export const g4 = styled.div`
grid-area: g4;
text-align: left;
`;

export const g5 = styled.div`
grid-area: g5;
text-align: right;
`;



